services:
  postgres:
    image: postgres:13
    container_name: GDO_postgres
    environment:
      POSTGRES_USER: GDO
      POSTGRES_PASSWORD: GDO!
      POSTGRES_DB: gdo_db
    ports:
      - "5437:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: